title: Suraj Dayma
description: Robotics & Autonomous Systems Student | Plaksha University
email: suraj.dayma.ug23@plaksha.edu.in
baseurl: ""
url: ""
# theme: minima
theme: jekyll-theme-cayman     # Modern with gradient header
# theme: jekyll-theme-slate      # Dark theme, professional
# theme: jekyll-theme-architect  # Bold headers, clean layout
# theme: jekyll-theme-midnight   # Dark with sidebar
# theme: jekyll-theme-minimal    # Ultra-minimal, elegant
# remote_theme: pages-themes/modernist@v0.2.0  # Clean, professional

# Social links
github_username: suraj1102
linkedin_username: surajdayma

# Navigation
header_pages:
  - index.md
  - about.md
  - research.md
  - projects.md
  - contact.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from