---
title: "High Resolution Air Quality Monitoring"
subtitle: "Digital Terrascope Initiative"
description: "A network of affordable, high-resolution IoT air quality monitors across the Tricity region, providing real-time pollution data for research, community awareness, and policy."
categories: [Research]
order: 2
author:
  - name: Arnav Kapoor
    url: https://www.linkedin.com/in/arnav-kapoor-9361a3112/
    affiliation: Plaksha University
  - name: Mihir Narula
    url: https://www.linkedin.com/in/mihirnarula/
    affiliation: Plaksha University
  - name: Suraj Dayma
    url: /
    affiliation: Plaksha University
---

::: {.link-row}
[<i class="bi bi-file-earmark-text"></i> Project Document](https://docs.google.com/document/d/1dyaCyCE1xLzGSbYHfhus8qxrCDiPNgCcAdTmXJ1JWGg/edit?usp=sharing)
:::

*Mentor: [Dr. Srikant Srinivasan](https://plaksha.edu.in/faculty-details/dr-srikant-srinivasan), Professor & Dean of Academics, Plaksha University.*

::: {.highlight-panel}
## Overview

Air pollution in India is a major challenge, especially in cities where local spikes often go undetected due to sparse monitoring. Existing government stations are too few to capture these variations, and AQI metrics often overlook harmful gases.

Our project tackles this by building a network of affordable, high-resolution IoT air quality monitors across the Tricity region. This will provide detailed, real-time pollution data to support research, community awareness, and policy decisions.

This work is part of the broader 'Digital Terrascope' initiative for smart city analytics, which also includes meteorological and traffic projects.
:::

Key components:

- IoT Node Development
- Calibration
- Data Infrastructure
- Web Platform
- Data Analysis

## Detailed Description

You can read a more detailed description of the problem and the work conducted so far [here](https://docs.google.com/document/d/1dyaCyCE1xLzGSbYHfhus8qxrCDiPNgCcAdTmXJ1JWGg/edit?usp=sharing).
